version: '2.4'

services:
  postgres:
    image: postgres:11.2
    container_name: postgres
    command: ["postgres", "-c", "max_connections=200", "-c", "effective_cache_size=4GB", "-c", "shared_buffers=2GB", "-c", "synchronous_commit=off", "-c", "log_statement=none", "-c", "checkpoint_timeout=600", "-c", "max_wal_size=30GB"]
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=jokesdb
      - TZ=Europe/Berlin
    ports:
      - 5433:5432
    restart: always
    mem_limit: 4g
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} psql --username=$${POSTGRES_USER} --host=localhost --dbname=$${POSTGRES_DB} --command='\\q'"]
      interval: 30s
      timeout: 5s
      retries: 3
